### ISSUE TITLE
Plugin not showing within Jenkins server

### ISSUE THREAD

**Issue by itshemant4u** [yandex-qatools/juseppe#15]
I have launched Juseppe with help of docker on a separate server. On the same server, I have also set up port mapping using:  

`docker run -d --name juseppe -v /var/lib/juseppe/plugins:/juseppe/plugins -p 80:8080 -e JUSEPPE_BASE_URI=http://juseppe.company.net lanwen/juseppe`  

It seems to be setup correctly because when i upload a new plugin in `"/var/lib/juseppe/plugins" directory`, I can see that plugin becomes available `at http://dockerhost:80/update-center.json `

After that within Jenkins server, I `configured "UpdateSites Manager plugin". ` I have specified ID, URL of the update site and CA for the site.
Still, I don't see plugin within Jenkins server. I cannot find it under `Manage Plugins --> Installed`

**Comment by lanwen** [comment]
Anything in jenkins logs? Usually it writes something like `Obtained the latest update center data file for UpdateSource juseppe`

**Comment by itshemant4u** [comment]
I don't see any such message within logs of Jenkins server. I dont see any message at all within logs of Jenkins server. However, I do see that `update-center.json` is updated successfully on the updateSource site.  Please help me find out what might be missing and why I don't see plugin within Jenkins server.

**Comment by lanwen** [comment]
Are you using jenkins inside docker container? I'll try to reproduce it tomorrow in the evening.

**Comment by itshemant4u** [comment]
I have installed Jenkins on a server. However, for Jenkins slave I am using Docker containers. I am not using docker for Jenkins master

**Comment by lanwen** [comment]
What jenkins version and update site plugin do you use?

**Comment by itshemant4u** [comment]
I am using ver. 1.628 of Jenkins and version 2.0.0 of update-sites-manager

**Comment by lanwen** [comment]
seems that something prevents your jenkins to start fetching uc.json from juseppe

What i'm doing:
`docker run --name juseppe --rm -v ~/Desktop/plugins/:/juseppe/plugins/ -e JUSEPPE_BASE_URI=http://dockerhost -p 80:8080 lanwen/juseppe`

`docker run --name jenkins  -p 8080:8080 -l juseppe:dockerhost --rm --link juseppe:dockerhost jenkins:1.625.3`
(not found exact 1.628 as container)

then install update-site manager plugin and setup it:
![manage updatesites jenkins 2016-03-19 03-09-02](https://cloud.githubusercontent.com/assets/1964214/13895064/fa522156-ed7f-11e5-8d35-a01ec6b6e468.png)

then back to http://dockerhost:8080/pluginManager/ and click to check btn.

Then in jenkins logs i see: 
```
Mar 19, 2016 12:04:30 AM hudson.model.UpdateSite updateData
INFO: Obtained the latest update center data file for UpdateSource default
Mar 19, 2016 12:04:30 AM hudson.model.UpdateSite updateData
INFO: Obtained the latest update center data file for UpdateSource juseppe
```

in juseppe logs:
```
2016-03-19 00:04:30 INFO  RequestLog:60 - 172.17.0.3 - - [1458345870065] "GET /update-center.json?id=juseppe&version=1.625.3 HTTP/1.1" 200 10055
```

Plugins available in plugin list with help of search.

Check that: 
- you can connect to juseppe from jenkins host (go to jenkins via ssh and call `curl '<your_juseppe_url>'`
- in tcpdump check jenkins sends any data to juseppe
- you correctly setup cert
- your plugin can't be found with help of search in plugins list

then tell if any news
