### ISSUE TITLE
Make Juseppe core compatible with Jenkins environment

### ISSUE THREAD

**Issue by oleg-nenashev** [yandex-qatools/juseppe#22]
Use-case: Embed Juseppe into Jenkins plugin in order to generate on-demand update centers.

Currently it's not possible to include the library due to slf4j and bouncycastle conflicts

**Comment by oleg-nenashev** [comment]
Some bits from my local fork: https://github.com/yandex-qatools/juseppe/pull/21

**Comment by lanwen** [comment]
Fixed by #20
