### ISSUE TITLE
ServeCommand serves only *.hpi files

### ISSUE THREAD

**Issue by oleg-nenashev** [yandex-qatools/juseppe#28]
IMHO the Windcard should support *.jpi as well

https://github.com/yandex-qatools/juseppe/blob/0e571d6ab8f0eb1b445a8d7af775d0e2d0003f1f/juseppe-cli/src/main/java/ru/lanwen/jenkins/juseppe/cli/ServeCommand.java#L27

**Comment by lanwen** [comment]
Thanks!
