### ISSUE TITLE
UpdateSiteGen does not pass its properties to Signer

### ISSUE THREAD

**Issue by oleg-nenashev** [yandex-qatools/juseppe#31]
In 1.1.0 UpdateSiteGen initializes Signer by a default constructor. This constructor takes <code>Props.populated()</code>, which may differ from settings instance passed to UpdateSiteGen.

In my case I want to pass certificate/key paths via Props, but it does not work anymore.

Fixing it

**Comment by lanwen** [comment]
Already fixed in #29 
`public Signer(String privateKeyPath, List<String> certificatePaths, List<String> rootCAPaths)`
