### ISSUE TITLE
Signature failure

### ISSUE THREAD

**Issue by spland30** [yandex-qatools/juseppe#33]
Downloaded and installed latest Juseppe Update center.
Default URL = http://spl-myserver-udc01/update-center.json

This works fine when I deploy using tomcat. It fails miserably when I try to run using the builtin Winstone.... 

Click on Check Now button and it fails with the following error. It fails with certificate enabled and certificate disabled. Of course... that is not the default URL. This is really bad that there is no documentation on how to resolve this.

********
Signature verification failed in update site 'default' 

SEVERE: ERROR: Signature verification failed in update site &#039;default&#039; <a href='#' class='showDetails'>(show details)</a><pre style='display:none'>java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors<br>	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:153)<br>	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)<br>	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)<br>	at org.jvnet.hudson.crypto.CertificateUtil.validatePath(CertificateUtil.java:93)<br>	at jenkins.util.JSONSignatureValidator.verifySignature(JSONSignatureValidator.java:76)<br>	at hudson.model.UpdateSite.verifySignature(UpdateSite.java:225)<br>

**Comment by oleg-nenashev** [comment]
Do you use https://wiki.jenkins-ci.org/display/JENKINS/UpdateSites+Manager+plugin ? This plugin supports disabling certificate checks for particular repos. Another option is to generate a proper certificate with supported anchors.

**Comment by oleg-nenashev** [comment]
For the reference, there is an RFE for built-in untrusted certificate generation it in #23

**Comment by spland30** [comment]
Yes, I have this plugin installed and it fails with the same message with or without the check box enabled.

**Comment by spland30** [comment]
This is the command I use to generate the certificate. As described above tomcat works winstone doesn't.

openssl genrsa -out $JUSEPPE_HOME/certs/juseppe-udc.key 2048 && openssl req -nodes -x509 -new -key $JUSEPPE_HOME/certs/juseppe-udc.key -out $JUSEPPE_HOME/certs/juseppe-udc.crt -days 1056

**Comment by oleg-nenashev** [comment]
Just to make sure... Do you have a correct Jenkins URL specified in global settings when you run in Winstone? And do you really use Winstone? Newest version bundle Jetty by default

**Comment by spland30** [comment]
I'm using the winstone version that is bundled with Jenkins 2.5

**Comment by spland30** [comment]
The default URL and Custom update sites are set to the same URL http://spl-myserver-udc01/update-center.json. This is our internal only Update Center.

**Comment by spland30** [comment]
We are running on Ubuntu 14.04 if that makes any difference...

**Comment by spland30** [comment]
One other note. We are not using docker for juseppe. We have downloaded and compiled juseppe from the git repo.

**Comment by spland30** [comment]
Sorry, one more piece of info. I run the update center on one image and the jenkins master on another image. The jenkins master fails with error listed above when running jenkins behind winstone/jetty.

**Comment by spland30** [comment]
After wasting about a day poking around on this stuff. I finally got the stupid thing to work. The certificate for the default URL (defined by --webroot=/var/cache/jenkins/war) resides in /var/cache/jenkins/war/WEB-INF/update-center-rootCAs/jenkins-update-center-root-ca. I believe this is the certificate for the jenkins central repository. I replaced this certificate with the certificate for our update center. And now it works. I'm not sure if this is top-secret information, but It would be really nice someone documented this somewhere so nobody else wastes a day and half trying to figure out what the issue is.

**Comment by oleg-nenashev** [comment]
Sorry for not responding immediately - was at meetings.
Could you please create a follow-up improvement issue?

Actually I doubt that patching of cached files is a right approach. Any cache cleanup/WAR update may wipe the changes

**Comment by lanwen** [comment]
Here some info about place for certs
https://github.com/ikedam/backend-update-center2/wiki/How-to-create-your-own-Jenkins-Update-Center#put-your-certificate

But `Update site manager plugin` should solve same issues of the fly. Dunno why it not worked for you.

**Comment by spland30** [comment]
Excellent! Thank you for the responses and the link. This is a much better link than what I was using.

**Comment by Hermain** [comment]
Did not work for me. Placing my company certs in either place didn't help
