### ISSUE TITLE
Jenkins - Update Center - Updates

### ISSUE THREAD

**Issue by sathomps** [yandex-qatools/juseppe#37]
I'm currently running this internally to host Jenkins plugins.  While the plugin will show up as available, when a new version is pushed to the update site, I don't see the new version in Update Center->Updates.

**Comment by lanwen** [comment]
You can use history endpoint to ensure your plugin is scanned correctly. 
Please provide output of both update-center and history endpoints

**Comment by sathomps** [comment]
It appears that the history is being overwritten.  The plugin was on 3.0.0 and I updated it to 3.0.1
```{
  "releaseHistory": [
    {
      "date": "Dec 04, 2017",
      "releases": [
        {
          "gav": "plugin:3.0.1-SNAPSHOT (private-8ab69d8b-xxx)",
          "url": "http://plugin-jenkins.hpi",
          "timestamp": "2017-12-04T18:26:34.00Z",
          "title": "plugin-jenkins",
          "version": "3.0.1-SNAPSHOT (private-8ab69d8b-xxx)",
          "wiki": "http://plugin-jenkins"
        }
      ]
    }
  ]
}
```
```
updateCenter.post(
{
  "updateCenterVersion": 1,
  "id": "update_center",
  "plugins": {
    " plugin-jenkins": {
      "excerpt": "",
      "url": "http://plugin-jenkins.hpi",
      "releaseTimestamp": "2017-12-04T18:26:34.00Z",
      "buildDate": "Dec 04, 2017",
      "version": "3.0.1-SNAPSHOT (private-8ab69d8b-xxx)",
      "title": " plugin-jenkins",
      "wiki": "http://plugin-jenkins",
      "requiredCore": "2.7.3",
      "builtBy": "xxx",
      "name": " plugin-jenkins",
      "group": "plugin",
      "dependencies": [
        {
          "name": "workflow-aggregator",
          "version": "2.5",
          "optional": false
        }
      ],
      "developers": []
    }
  },
);
```

**Comment by lanwen** [comment]
New plugin doesn't appear even after force update of available plugins was pressed?

**Comment by sathomps** [comment]
I assume that you mean clicking the "Check Now" button within the UpdateCenter?

No it doesn't appear in the Update section.  Does show up in available/installed depending on the state of the plugin.

**Comment by sathomps** [comment]
Any updates to this issue?

**Comment by lanwen** [comment]
I can't reproduce

**Comment by sathomps** [comment]
Any tips on debugging this more from my side?

**Comment by lanwen** [comment]
Try clean instance first. Watch logs of juseppe and jenkins. They both should indicate communication. Try first with only one plugin hpi in directory, then add new and watch what happens. Try jenkins "check now" btn after that. Post logs here after.

**Comment by sathomps** [comment]
It appears that this was an issue with the certificate generated

`Invalid Certificate: signed overrun`

The plugin would display as available but the update center would not process correctly.
