### ISSUE TITLE
Wrong port display in log

### ISSUE THREAD

**Issue by etiennebatise** [yandex-qatools/juseppe#38]
Hi,

I have built the latest the master and I need to run the jar on port 9090 with the following command:
```bash
JUSEPPE_PLUGINS_DIR=/opt/jenkins/plugins/ JUSEPPE_BIND_PORT=9090 java -jar /opt/juseppe/juseppe-master/juseppe-cli/target/juseppe.jar -w serve
```

**Everything works fine**. Simply, the server-boot log displays the wrong information:
```
2018-02-09 16:56:15 INFO  Started ServerConnector@52a5e68a{HTTP/1.1}{0.0.0.0:9090} 

...

2018-02-09 16:56:16 INFO  UpdateSite will be available at http://localhost:8080/update-center.json
```

The url displayed should be `localhost:9090`.

**Comment by lanwen** [comment]
You should change `JUSEPPE_BASE_URI` also by yourself - it needs to generate right links in update-json.

**Comment by etiennebatise** [comment]
I get it now, thanks !
